raw_data:
  name: ./data/raw.csv
clean_data:
  name: ./data/clean.csv
  json: ./data/clean.json
  used_fields:
    - Title
    - Podcaster
    - Author
    - Total
    - Status
    - Time
    - Ship or Main Character
    - Archive/Blog Link
    - Spotify
    - Third Link
    - Pairing name
    - Date Podfic Published/Updated
    - Date Fic Published
    - Fic Link
  link_fields:
    - Archive/Blog Link
    - Spotify
    - Third Link
website:
  data: ./data/sheet.csv
  table_entries_per_page: 100
  autocomplete_max_length: 40
